name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Set up Docker Buildx (for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 4: Cache Docker layers (to speed up the build)
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Step 5: Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .  # The directory to build from (typically the root of your repo)
        file: ./Dockerfile  # Path to your Dockerfile (if it's in the root, you can omit this)
        push: true  # Push the image to Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/opensearch:${{ github.sha }}



